const util = require('../util.js');

module.exports = {
	name: 'quote',
	description: 'Gets A Quote From The Real Slickrick',
	aliases: ['q', 'qu'],
	args: false,
  usage: '<optional thing to search for in quote list>',
	execute(client, message, args) {
    var requester = message.guild.members.get(message.author.id).displayName;
    
    if (args) {
      filteredQuotes = []
      filteredQuotes = quotes.filter(quote => quote.toLowerCase().includes(args.join(' ').toLowerCase()));
      if (filteredQuotes.length > 0) {
        var randomQuote = filteredQuotes[util.getRandomInt(0, filteredQuotes.length)];
      } else {
        var randomQuote = quotes[util.getRandomInt(0, quotes.length)];
      }
    } else {
      var randomQuote = quotes[util.getRandomInt(0, quotes.length)];
    }
    

    var personalizedQuote = util.personalize(randomQuote, requester);

    var rickifiedQuote = util.rickify(personalizedQuote);

    message.delete();

		return message.channel.send(rickifiedQuote)
	},
};

const quotes = [
  
  'it is large. and feels great. so...?',
  'why did you ban fiona? she is my friend. fiona! come back.',
  'but if i was 14 i would of been your bf by now.',
  'placeholder is black now? surgery is real. gosh.',
  'i remember when i had my first mcdonalds meal, i always wanted my toy instead of the actual meal, good days my friend, good days.',
  'my rear rectum hurts.',
  'who runs the world? emos.',
  'i\'m so bendy like a straw.',
  'if you are seeking infinite, it\'s like wanting to go to the moon with a ball of socks, isn\'t it? that is the mind of humanity right now.',
  'placeholder\'s yummy short cakes.',
  'placeholder, you\'re awesome.',
  'you haven\'t seen me yet.',
  'do the uncle ricky. :coo:',
  'placeholder \'s profile looks like it was made by a retard. but mine looks like it was made by an artist. which is me.',
  'am i the only nigg-censored by liberal snowflakes- here?',
  'nothing, nothing at all',
  'i miss placeholder.',
  'i will elaborate my claim soon.',
  'that is incorrect',
  'God made you who you are biologically, genetically and physically unique at birth just as anybody else but the mindset that you construct is based on your individual own self which isn\'t necessarily something God has set in you.',
  'You will not face the consequences of my desires by doing what you want to do. That is up to God.',
  'we live under the free will.',
  'He was a dissident of the society in which he lived in.',
  'jesus wasn\'t all-accepting.',
  'Does that mean we must sacrifice the truth in order to gratify the senses of your sentiment? Jesus is the Truth.',
  'The truth is not subjective, only sentiments are.',
  'You can\'t be what you\'re not, even with a little bit of dedication and determination. You can\'t be what you want.',
  'Are you pointing out a reference to me that\'s about me?',
  'Solitude is my oasis.',
  'You are not forced to be with a person unless you live dependently.',
  'Try not to hold a grudge on them because it does nothing but vacuums your henergy. If he is stubborn after insisting then deal with them no longer.',
  'Are you willing to continually and consciously offend your friend? If so then you\'re not a true friend.',
  'You shouldn\'t be obliged to change it as long as it\'s not offensive.',
  'I acknowledge you placeholder.',
  'Yet he called me ugly',
  'What is ugly?',
  'If the world hates you, keep in mind that it hated me first. If you belonged to the world, it would love you as its own. As it is, you do not belong to the world, but I have chosen you out of the world. That is why the world hates you. ~ Words of Christ.',
  'truth hurts',
  'You will appear more masculine if you work out more.',
  'i\'m slim and fit.',
  'I\'m neither fat, chubby nor skinny.',
  'Okay, but is there anything that\'s a part of my personality that indicates that I don\'t work out? Because I do.',
  'Yeah, this explains why primitive men rarely had any sort of heart diseases or diabetes. We were formed out of the dirt to work along with our hands and feet to make progress.',
  'I barely joke around.',
  'You can\'t magically remove your emo instincts once you turn emo. You can only diminish the symptoms of being emo.',
  'I still get my ups and downs.',
  'You will see content that wasn\'t in existence a few decades ago.',
  'Incredulous. For example, if you look at current porn.',
  'People\'s perversion on sex has been on the increase during the past decades.',
  'It feels perverted.',
  'It sounds like you\'re practicing or preparing incestuous sex to me by using that terminology which is wicked. It wouldn\'t make a difference if a daughter were to have sex with her own father and call him \'daddy\'.',
  'I love you dearly.',
  'You\'re bitter-sweet.',
  'Kindness is a portion of your inner-beauty and that\'s what you partially have.',
  'I merely like to express my opposed belief, that\'s all.',
  'I\'m nice to you placeholder.',
  'Beauty doesn\'t age. Beauty is a factor of your inner self.',
  'First you must know that the primary reason of why guys flirt with girls is mainly because they\'re outwardly attracted to them. They value appearance above inner affection. I rather have a girl who loves me for who I am rather than what I look like. I advise you not to trust guys who are flirting with you because you know what they want, and it won\'t last long. If you know what I mean.',
  'I wouldn\'t lie to you, I love you all.',
  'i\'m just being real',
  'Yes, I know the fun song.',
  'I don\'t tolerate bondage.',
  'You never know what tomorrow may bring.',
  'Life is full of unexpected consequences.',
  'placeholder, get tested or rest it.',
  'Control your inclinations. and thy will be fine.',
  'You shouldn\'t perceive things like that.',
  'Who is Satan to you?',
  'Why lie about nonsense?',
  'placeholder, your characterization depicts confusion. You\'re truly an unstable individual.',
  'It\'s not clever to prioritize sex.',
  'This disappoints me a lot.',
  'Now placeholder has the power to silence me.',
  'why are you deleting my messages? Is this a hate/love thing?',
  'The reason why I want to post this is because I want to aspire you guys. It\'s all love at the end of the day.',
  'It\'s a good thing it was preplanned, thus still remaining in my memory.',
  'You\'re not my master.',
  'You guys aren\'t ready for the harvest.',
  'Who are you to me?',
  'I do not fear you.',
  'You will not silence me.',
  'What is the long-term effect of too much information? The polarization of the electorate? The acquirement of false data?',
  'Every day has a different flavor.',
  'People have to understand: are you using your device or is your device using you? Can you put it down? Can you turn it off?',
  'All of the information that we obtain, whether it\'s from television or from your phone used to be news but now it\’s opi-news, When reporters, anchors and so-called \'experts\' (3 on the left and 3 on the right) are exchanging words in the discussion table, they’re not necessarily reporting news. I rather label it as opi-news.',
  'Sadly, this occurs over and over again in endless cycles. They do it to sell, make profit and capture viewership. This is called "the law of attraction".',
  'So, what is the long-term effect of too much information? We have to ask ourselves “what is it doing to us?”.',
  'If you don’t read the newspaper, you’re uninformed. If you do read it, you’re misinformed. So, what is the long-term effect of too much information?',
  'That’s the responsibility you should all have, to tell the truth and not just to be first.',
  'We live in a society where people are more interested in lies because they seem more entertaining. Who cares about knowing the truth anymore? It’s boring.',
  'Anything you practice you’ll get good at, including bs.',
  'placeholder, here\'s a problem that\'s between us. I\'ve made several attempts in trying to make you understand my belief that I regard as true by respectfully providing a full and complete argument that sits with reasoning. ',
  'The question is: How have you replied politely? Have you perfectly disproved my argument? The answer is: no because you don\'t possess a counter argument. You vilified me instead.',
  'You\'re too focused on how you feel and what you think and that wanders you away from the truth. You are led astray.',
  'The truth is the truth and we must live in the truth. The truth is NOT correlated within our opinionated perspectives.',
  'I\'m a type of person who abides by the truth despite if my emotions or thoughts perceives it the other way around. I think you should do the same.',
  'You should sacrifice your comfort zone and comply with reality instead of living a lie because that makes you a fraud by not doing so. Period.',
  'That\'s something you would say to me.',
  'I\'m in a careless mood right now.',
  'I didn\'t give you permission but okay.',
  'What is it that you want from me this time?',
  'Lucky O\'s.',
  'I really can\'t get how poor people can be fat though if they don\'t have that much money.',
  'I can\'t close my eyes without having somebody mentioning my name.',
  'I haven\'t seen anyone provide any logical argument or reason that explains how abortion isn\'t equivalent to murder. You are highly easily likely to believe that abortion isn\'t equivalent to murder if you don\'t knowledge in biology or in medicine.',
  'Do you actually believe that abortion isn\'t equivalent to murder?',
  'Oh dear, I\'m going to hibernate again.',
  'I don\'t chase diseases.',
  'Baking pizza on the oven.',
  'If you feel hurt by some opinion I\'ve mentioned in a respectful way then you\'re acting immature about it. Period. You can proclaim to my the most upsetting opinion to me and I won\'t respond animalistic or inhumane.',
  'I\'ve been despised enough here for believing what I believe but I haven\'t shown you hatred in any way, shape or form.',
  'You\'re treating me in such a horrifying manner I will never treat you in return.',
  'Only a bullet can stop me.',
  'You did not convince me.',
  'Okay? Your point is... ?',
  'Grow in maturity as you age in physique.',
  'Don\'t let fear take control of you. That is a sign of weakness.',
  'There wouldn\'t be such a thing as "learning your lesson" if all actions are good but we tend to learn in many different ways.',
  'I don\'t regret anything that has happened in my past, including the negative things. I don\'t even consider them as a bad memory. I rather view it as a lesson. I live, I learn and I move on.',
  'Young people are always more accepting in whatever age or generation and that\'s because they\'re naïve due to their lack of experience in life and in knowledge.',
  'CNN is worse than Fox News.',
  'Still no change from you, eh. After all of those years.',
  'Evening fellow ice cavers.',
  'Life itself is mysterious.',
  'How did the universe began? How was it formed? How did the process of so called \'evolution\' lead to orderly and organized galaxies, planets, moons, the rotation and circulation of comets.. etc.. Those are questions we can\'t answer with affirmation. That\'s why scientists create hypothesis leading to theories. That\'s the maximum point to what we can believe after spending enormous time and effort in finding the answers to these sorts of questions. ',
  'In response to your reply, we can\'t observe the unseen except if it\'s detectable like oxygen and supposedly \'dark matter\'. This topic is rather a matter of \'if\'. You or even I, or even the smartest scientists out there can not set forward evidence that proves that.',
  'I tend not to believe everything I see or hear, but I don\'t tend to disbelieve them automatically. I try to believe them 50% at first glance, then I try to see if I can provide anything that demonstrates whether or not the premise or deduction is reliable or unreliable.',
  'We didn\'t choose to be born. We didn\'t choose our sex or gender. We didn\'t choose who our parents were/are. We didn\'t choose which country we live in. We didn\'t choose to be alive or in existence.',
  'I sometimes ponder and reflect about where I was born, where I was raised and where I currently live and I can\'t be more pleased than how I\'m feeling now regarding that.',
  'However, at times I also do think about how my life would be if I was born, raised or lived in another country, especially in a 3rd world country which is horrendous and it feels as frightening as it sounds, living life without the freedom and values America portrays but I can\'t confirm who I will be, how I will think or what I will do but I\'m sure that my attributes and characterization depending on what country I\'m from will pertain to its culture, politics, religion, environment.. etc.. There is only speculations in dialogues as these that are subjective.',
  'We live in a world that has a population of almost 8 billion people and they all vary from different nations, countries, cultures, genders, religions and so on that influences how they all live, think and interact with others. You have to understand, placeholder, that most people aren\'t in agreement with what/who you think you are and your perspectives and that will never change. ',
  'Face it, some things will indisputably never change in life, no matter how hard people try. There has always been an opposition party. There will always be black and white, hot and cold.. etc...',
  'You have to learn to live with that. I know it may feel like a burden or it might distress you but that\'s the reality of the world we live in.',
  'We live in a dark world where evil will always continue to exist as long as the earth spins.',
  'I\'m sure many people here resemble the same viewpoints as I do and they\'re perhaps too frightened to speak their minds or how they feel about a certain notion due to being backlashed but hey, I\'m not like them. I stand by my honesty and freedom of speech. I would have lied to all of  you but rather I didn\'t because I abide by my morals.',
  'At the end of the day, placeholder is displaying hatred whilst I\'m not.',
  'I\'m racially mixed for your information, thanks.',
  'There is something that is always constant in life and that is change, and change.',
  'We all go through changes, physically, mentally and psychologically.',
  'At times we choose to change whereas in other circumstances we change without our realization within our subconscious mind.',
  'Will I change? yes but I am cautious to what I will believe in. It depends on whether or not the substance is plausible enough according to my own behaviorism, but.... I can\'t guarantee anything concerning that since anything is possible.',
  'All I can say is that I\'ll be the judge of whatever I\'ll accept as fact or fiction, and with tremendous of outside source of course.',
  'I don\'t detest you, I really don\'t. We merely have contrary perspectives and mindset but that shouldn\'t set us apart. You said you dislike me only because I don\'t have your standpoint. Doesn\'t that sound rubbish to you? I don\'t hate you simply because you don\'t share my beliefs.',
  'That\'s why I cease to resume in this dialectic, it appears to be endless. It doesn\'t seem like we can reach an impasse.',
  'Again, re-read my post if you think I believe that. You\'re being arrogant placeholder.',
  'I recommend everybody to read or re-read the large post I\'ve put out that regards my response to placeholder. I\'m about to rest my case.I recommend everybody to read or re-read the large post I\'ve put out that regards my response to placeholder. I\'m about to rest my case.',
  'I could careless what people say to me unless they\'re trying to correct me. I\'m a man of my word. I keep them, mark them unless \'proven\' otherwise.',
  'Claiming and stating things without providing elaboration, explanation, evidence or proof is equivalent to making dull/void declarations that are invalid, but if you were to send out anything that indicates a logical counter or riposte then that\'s fair enough.',
  'You are not what you feel. Feelings can be stirred by misapprehension. You are what nature determines you to be.',
  'You\'re *LITERALLY* putting words in my mouth, that\'s why I advise you to re-read my post.',
  'I respect everybody of all kinds, however I may not view the world the same way they perceive it. That doesn\'t give me the right to mistreat them in a inhumane manner.',
  'That\'s all I\'m going to say, for now.',
  'Please, and please... and seriously... re-read what I\'ve posted.',
  'Nature doesn\'t lie. Sometimes the course, productivity and constant change in nature is the source of our comprehension about the outside world. ',
  'For instance, I\'m 22 and if I were to claim that I am 50 years old simply because I feel like I\'m that age then that should be justified by that concept of yours. This is bogus, it doesn\'t make sense and it doesn\'t set in with reasoning.',
  'Many people dislike me because I speak my mind, but I do so since there\'s freedom of speech and you will not take away that freedom from me.',
  'Enough said, placeholder. Please stop countering his argument.',
  'You don\'t have any idea yet.',
  'You don\'t have much comprehension about this.',
  'DAMN FUCKING RIGHT',
  'I understand everything you\'re saying.',
  'placeholder, man, you must have been through lots of shit in order to have that kind of insight. Much respect.',
  'I didn\'t make any contradictions.',
  'I think there are many beautiful transgender women.',
  'So, you think I\'m lying when I said that?',
  'That doesn\'t make any sense.',
  'How am I transphobic if I\'m attracted to them?',
  'Why do I always get treated unfairly by you guys? It\'s been 9 years.',
  'I came back after years of absence and this is the welcome I receive?',
  'I\'m racially mixed for your information, thanks.',
  'Take notes from placeholder. Because everything he\'s saying is true and it pertains to me.',
  'placeholder, that\'s where my sexual frustration comes from.',
  'You have to understand that there are people who have opposition beliefs contrary to what you believe.',
  'Btw, placeholder, I don\'t hate you.',
  'damn right placeholder.',
  'Your response is?',
  'Carry on mate.',
  'Why are you switching the topic?',
  'People used to bash at me because I speak my mind. That\'s why you people kept banning me, but guess what? Freedom of speech.',
  'Other than feelings, you\'re not who you think you are',
  'But let me tell you something.',
  'Why express hatred towards me?',
  'I don\'t even know what you look like.',
  'Oh, so that\'s your defensive strategy?',
  'Excuse my language, but I\'m fucking fed up with this world. It\'s literally upside down.',
  'That\'s why I\'m done with society and with people, it\'s due to people like you.',
  'You can\'t say something like that to somebody who is suicidal because if the person does commit suicide, you will regret every sort of maltreatment you\'ve executed towards that person. That makes you look rubbish and cruel. ',
  'I don\'t want to deal with people like you if you\'re truly showing me your true colors.',
  'Sorry, I\'m too overwhelmed right now. I\'m speechless.',
  'I could go on and on talking about this, but I rather limit myself.',
  'I don\'t know, I\'m just being paranoid ok.',
  'I told you my reputation would be worse and that you would portray me as a monster.',
  'It\'s not the entire story, but I\'ve told you the basics.',
  'I\'ve been falsely accused.',
  'WHY ARE YOU ALWAYS AGAINST ME',
  'I THINK IT IS WRONG AND IMMORAL',
  'Pretty much accurate, but I really wanted to see you guys.',
  'Gosh, sorry. I can\'t say it. I don\'t want to waste your time in this.',
  'It\'s the other way around.',
  'I\'m being tormented by my thoughts of insanity.',
  'I never knew what true paranoia is until recently.',
  'I\'m a guy with lots of secrets that hasn\'t been told and it\'s piling up persistantly.',
  'I cringe.',
  'I hate looking back at who I used to be.',
  'I only follow the word.',
  'I don\'t believe in the power priests claim they have.',
  'Death is the entrance of our second life.',
  'I rather feel the pains of misery than to be drunk in the state of happiness.',
  'Death is tasteful',
  'Truth is, life is strange.',
  'I barely find anything impressive.',
  'Being emo left a scar in me.',
  'Omg... placeholder! <:red:545371189741223956> Stop it....',
  'I know some pays well but it\'s not my preference.',
  'I don\'t like dirty jobs. Yuck, ew.',
  'Yeah, I\'m still deliberating on that decision.',
  'I mainly want to study theological studies.',
  'Wait.. what do you mean by that, placeholder? You\'ve been there as well?',
  'Is that a subliminal or something.',
  'It\'s creepy, omg.',
  'That\'s something I\'m not sure yet and it has been killing me lately.',
  'I don\'t think placeholder likes me like that.',
  'Yeah, but I rarely communicate with anybody.',
  'Well, hmm. Let me see. None. I\'ve been in deep isolation and solitude for the past few months, pondering upon myself about the mysteries of life.',
  'I don\'t feel like I have the freedom to say whatever I want anymore on a flash chat due to paranoia.',
  'That\'s why I\'m constantly hinting you guys.',
  'placeholder knows one of my struggles. I get confused.',
  'I\'ve done that and I feel like God hasn\'t left my side.',
  'This is making me feel uncomfortable, I don\'t condone any of those stuff.',
  'See, I\'ve said too much.',
  'I feel like I\'m being interrogated by you guys as I was recently.',
  'It doesn\'t deal with sex or sexuality though.',
  'It\'s worse, tbh.',
  'It\'s too shameful to confess it.',
  'Woah there eager beaver.',
  'Wait, what\'s going on here.',
  'I wish I could speak of my issues but it\'s kind of too personal.',
  'I believe you\'re too embarrassed to admit that when you shouldn\'t be.',
  'I think you\'re that, placeholder, and I also think you\'re playing games.',
  'Well, not as much as I used to. I\'ve entered a crisis and it has affected me in every form you can possibly think of. But I\'m still of faith of course.',
  'Those were the days.',
  'I\'m LoW~S~Rick by the way.',
  'It\'s too defiance unto my belief.',
  'I wish I could but I\'m pretty occupied at the moment.',
  'Well, whenever I talk to people I always attempt to avoid the usage of slang language because slang language is an improper form of communication.',
  'Seemingly, the way people converse English is diminishing in terms of high vocabulary expressions due to the emerging slang language of texting and such.',
  'These days people are astonished of how well anyone can utilize and articulate English terms in both, words and vocals.',
  'Training should be the key.',
  'Whatever word that must be proclaimed to you shall be proclaimed and any dialectic with me is allowed if you have the interest to take that step.',
  'I suppose you rather pay more attention in class, rather than spending time with low paying employers in Walmart.',
  'Walmart is absolutely not an area of educational benefits.',
  'That was not my intention.',
  'and so I decided to come here and explore what is that I did not acquire.',
  'Greetings to you placeholder. It\'s been quite a long time since we have encountered',
  'Marvelous. It\'s great to reconnect with the TIC community, as I missed it.',
  'I ceased the habit of capitalizing the first of every word once I started to be less active on xat, which is the only online location in where I type in this manner.',
  'I am a Christian and will remain forever.',
  'Well placeholder, that is quite difficult to answer, considering we didn\'t have numerous conversation but I do recall having religious discussions.',
  'I remember back in the days when I used to say "I\'m the real Criz" while confronting someone whose name was/is Criz merely for the sake of joking.',
  'Thank you placeholder, I appreciate your kindness unlike the way you were in the past.',
  'This is Rick.',
  'wheres that placeholder dude',
];
